### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by thebarty** [fivetran/analytics-js-without-segment#1]
@fivetran: Looks like you have put some work into this.

Can you tell, what exactly you have done in OpenSourceAnalytics.js? Looks like you have modified it quite a bit in relation to SegmentCdnAnalytics.js.

Are you aware of this solution here http://www.ianww.com/blog/2017/08/06/analytics-js-standalone-library/

How is your solution better?

Are you using this in production?

**Comment by thebarty** [comment]
Just published https://github.com/thebarty/analytics-js-without-segment

**Comment by georgewfraser** [comment]
Hi @thebarty sorry I didn't get back to you sooner. I can't remember if I read [Ian Webster's post](http://www.ianww.com/blog/2017/08/06/analytics-js-standalone-library/) back when I did this; this repo is basically a demo, and I read a bunch of blog posts like that before I set it up.

One of the challenges I ran into is that you need to "bake" a different version of analytics.js depending on what integrations you intend to use. We were thinking that we would set up a simple server-side service that does that and CDN it under fivetran.com as a public service, to make it possible to use analytics.js with only client-side-code.

We've recently decided to adopt self-hosted analytics.js ourselves so we need to get this operational in the next couple weeks. How is your version of this going? Would you mind shooting me an email? My email is in my profile. We'd like to do whatever we can to support the community of people who are interested in using self-hosted segment. Segment is a great product but there are scenarios where people want to self-host, and I think there needs to be a community around it that's separate from the company.

**Comment by thebarty** [comment]
@georgewfraser I got my packages running in production. So far it works good. By the ay: You can use a public CDN service (see my packages for links). Hence you do NOT need to bake those versions - analyticsjs does the job for you.

The problem is that analyticsjs (as published by segment) is ONLY client-side - there is NO plug-and-play solution for the serverside. 

SERVERSIDE? If you check out the integrations that segment write (together with the open-source community) you can see that things are actually NOT as easy as they seem.

So I guess that this is where a self-hosted open-source solution comes in. Maybe catch server-side requests and route them thru the hosted server using the client's api. My first guess is that you will loose quite some time on getting server-side to work.

**Comment by georgewfraser** [comment]
My concern about using the public CDN version is that because it contains all the integrations baked-in, it's pretty big. But after looking at it I've realized it's only 58kb minified and gzipped, which I suppose is not big enough to really matter.

**Comment by thebarty** [comment]
Sounds right!

For inspiration:
This is the server-side package that segment uses to route data to its servers: https://www.npmjs.com/package/analytics-node
Github: https://github.com/segmentio/analytics-node

The code itself does not look too complicated. The question is: what happens on the server? Is there a simple trick to route using the server-events via the client's analyticjs?

@georgewfraser Shoot me a line if you're a step ahead.
